# Generated by Django 3.2.4 on 2021-09-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0002_addproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srno', models.IntegerField()),
                ('images', models.ImageField(upload_to='')),
                ('productname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='AddProducts',
        ),
    ]
