# Generated by Django 3.2.4 on 2021-09-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectApp', '0003_auto_20210916_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('productid', models.IntegerField()),
                ('userid', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='quantity',
            new_name='remainingquantity',
        ),
        migrations.AddField(
            model_name='products',
            name='totalquantity',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
